/*
 * This file has been auto-generated by the Generator C# app.  
 * Please adjust to meet YOUR requirements!!!!!
 * This is NOT intended to be the final version of the table or the final filename.  
 */