CREATE PROCEDURE [{0}].[CheckInsertViews]
AS 
BEGIN
    /*
     *  These select statements ensure that each loading insert view has the correct columns when the SSDT project is compiled. 
     *  This stored proc is auto-generated code.  Generated by Generator C# program which can be found at https://github.com/DrJohnT/MetadataGenerator 
     */
	{1}
END