create view {0}.{1}
as
/*      
 *  This view is auto-generated code.  Generated by Generator C# program which can be found in the \Code\Generator folder 
 */
select 
	(
		select  MAX(LoadDate)from   Logging.LoadLog
	)                                                 as ExtractDate,
	ISNULL(LLU.LoadDate, LLI.LoadDate)                as LastUpdatedDate,
	{3}
from qDm.dimPolicyOutward as A with (nolock)
	join		qDm.dimPolicy as POL with (nolock)
      on		A.dimPolicyId = POL.dimPolicyId
	join        Logging.LoadLog       as LLI with (nolock)
      on        LLI.LoadLogId = A.LoadLogId
    left join   Logging.LoadLog       as LLU with (nolock)
      on        LLU.LoadLogId = A.UpdatedLoadLogId
where           A.dimPolicyId > -1;    