create view {0}.{1}
as
/*      
 *  This view is auto-generated code.  Generated by Generator C# program which can be found at https://github.com/DrJohnT/MetadataGenerator 
 */
select {3}
from {2}.{1} as A with (nolock);
