create view {0}.{1}
as
/*      
 *  This view is auto-generated code.  Generated by Generator C# program which can be found in the \Code\Generator folder 
 */
select {3}
from {2}.{1} as A with (nolock)
	join    qDm.dimPolicy as POL with (nolock)
      on    A.dimPolicyId = POL.dimPolicyId
    left join    qDm.dimPolicyInwardXl as PXL with (nolock)
      on    A.dimPolicyId = PXL.dimPolicyId

